### ISSUE TITLE
v2

### ISSUE THREAD

**Issue by caarlos0** [fabioberger/coinbase-go#4]
any plans to implement api v2?

**Comment by gwpl** [comment]
ping

**Comment by cuotos** [comment]
am guessing not

**Comment by happilymarrieddad** [comment]
I need a version 2 so I'm going to write one. Here is the link
https://github.com/happilymarrieddad/coinbase-go-v2

**Comment by dant89** [comment]
I'm working in spare time on a refactor for V2: https://github.com/dant89/coinbase-go-v2
